networks:
  ltl-net:
    driver: bridge

services:
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    ports:
      - "${INFLUXDB_PORT_EXPORT:-8086}:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-admin123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-myorg}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-loadtests}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      # - ./influxdb/config/config.yml:/etc/influxdb2/config.yml
    networks:
      - ltl-net

  # influxdb-init:
  #   image: influxdb:2.6
  #   container_name: influxdb-init
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_TOKEN=${INFLUXDB_PASSWORD}
  #     - INFLUXDB_ORG=${INFLUXDB_ORG}
  #     - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
  #   networks:
  #     - ltl-net
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: |
  #     echo "Waiting for InfluxDB to be ready..."
  #     until influx ping --host http://influxdb:8086; do sleep 2; done

  #     echo "Fetching bucket ID..."
  #     BUCKET_ID=$(influx bucket list \
  #       --org ${INFLUXDB_ORG} \
  #       --token ${INFLUXDB_TOKEN} \
  #       | grep ${INFLUXDB_BUCKET} \
  #       | awk '{print $1}')

  #     echo "Creating DBRP mapping if missing..."
  #     influx v1 dbrp create \
  #       --db k6 \
  #       --rp autogen \
  #       --bucket-id $BUCKET_ID \
  #       --org ${INFLUXDB_ORG} \
  #       --token ${INFLUXDB_TOKEN} \
  #       || echo "DBRP mapping already exists"

  #     echo "Done."

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana/storage
    networks:
      - ltl-net

  telegraf:
    image: telegraf:1.28-alpine
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8125:8125/udp" # StatsD
    depends_on:
      - influxdb
    networks:
      - ltl-net
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    restart: unless-stopped

  k6:
    # image: grafana/k6:0.49.0
    build: ./k6
    container_name: k6
    working_dir: /k6
    volumes:
      - ./k6:/k6
      - ./scripts:/scripts
      - ./custom:/custom
    # El entrypoint se configura en el Dockerfile
    environment:
      - TARGET_API_URL=${TARGET_API_URL}
      - CONCURRENCY=${CONCURRENCY}
      - DURATION=${DURATION}

      - INFLUXDB_URL=http://influxdb:8086 # use the service name for inter-container communication
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    depends_on:
      - influxdb
      # - influxdb-init
    networks:
      - ltl-net

  artillery:
    build: ./artillery
    container_name: artillery
    working_dir: /artillery
    volumes:
      - ./artillery:/artillery
      - ./scripts:/scripts
      - ./custom:/custom
    environment:
      - TARGET_API_URL=${TARGET_API_URL}
      - CONCURRENCY=${CONCURRENCY}
      - DURATION=${DURATION}
      # Telegraf StatsD configuration
      - STATSD_HOST=telegraf
      - STATSD_PORT=8125
    depends_on:
      - influxdb
      - telegraf
    networks:
      - ltl-net

  toy-api:
    build: ./toy-api
    ports:
      - "${TOY_API_PORT:-5000}:5000"
    environment:
      - PORT=5000
    networks:
      - ltl-net

volumes:
  influxdb-data:
  grafana-data:
